package com.zed.xposed.demo.greedao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zed.xposed.demo.greedao.entity.WxChatInvokeMsg;
import com.zed.xposed.demo.greedao.entity.WxContact;

import com.zed.xposed.demo.greedao.dao.WxChatInvokeMsgDao;
import com.zed.xposed.demo.greedao.dao.WxContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wxChatInvokeMsgDaoConfig;
    private final DaoConfig wxContactDaoConfig;

    private final WxChatInvokeMsgDao wxChatInvokeMsgDao;
    private final WxContactDao wxContactDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wxChatInvokeMsgDaoConfig = daoConfigMap.get(WxChatInvokeMsgDao.class).clone();
        wxChatInvokeMsgDaoConfig.initIdentityScope(type);

        wxContactDaoConfig = daoConfigMap.get(WxContactDao.class).clone();
        wxContactDaoConfig.initIdentityScope(type);

        wxChatInvokeMsgDao = new WxChatInvokeMsgDao(wxChatInvokeMsgDaoConfig, this);
        wxContactDao = new WxContactDao(wxContactDaoConfig, this);

        registerDao(WxChatInvokeMsg.class, wxChatInvokeMsgDao);
        registerDao(WxContact.class, wxContactDao);
    }
    
    public void clear() {
        wxChatInvokeMsgDaoConfig.clearIdentityScope();
        wxContactDaoConfig.clearIdentityScope();
    }

    public WxChatInvokeMsgDao getWxChatInvokeMsgDao() {
        return wxChatInvokeMsgDao;
    }

    public WxContactDao getWxContactDao() {
        return wxContactDao;
    }

}
